import { Career, Faculty, Modality } from '../types';

export const faculties: Faculty[] = [
  { id: 'derecho', name: 'Facultad de Derecho y Ciencias Sociales', acronym: 'FDCS', dean: 'Prof. Dr. Carlos Gustavo González Morel', website: 'www.der.una.py', color: 'bg-red-800' },
  { id: 'medica', name: 'Facultad de Ciencias Médicas', acronym: 'FCM', dean: 'Prof. Dr. Osmar Manuel Cuenca Torres', website: 'www.med.una.py', color: 'bg-emerald-600' },
  { id: 'ingenieria', name: 'Facultad de Ingeniería', acronym: 'FIUNA', dean: 'Prof. Dr. Rubén Alcides López Santacruz', website: 'www.ing.una.py', color: 'bg-gray-700' },
  { id: 'economicas', name: 'Facultad de Ciencias Económicas', acronym: 'FCE', dean: 'Prof. Dr. Roberti Daniel González Martínez', website: 'www.eco.una.py', color: 'bg-blue-800' },
  { id: 'odontologia', name: 'Facultad de Odontología', acronym: 'FOUNA', dean: 'Prof. Dr. Rodolfo Perruchino Galeano', website: 'www.odo.una.py', color: 'bg-purple-600' },
  { id: 'quimicas', name: 'Facultad de Ciencias Químicas', acronym: 'FCQ', dean: 'Prof. Lic. Cynthia Saucedo de Schupmann', website: 'www.qui.una.py', color: 'bg-cyan-600' },
  { id: 'filosofia', name: 'Facultad de Filosofía', acronym: 'FFUNA', dean: 'Prof. Dr. Ricardo Luis Vicente Pavetti Pellegrini', website: 'www.fil.una.py', color: 'bg-amber-600' },
  { id: 'agrarias', name: 'Facultad de Ciencias Agrarias', acronym: 'FCA', dean: 'Prof. Ing. Agr. Jorge Daniel González', website: 'www.agr.una.py', color: 'bg-green-700' },
  { id: 'veterinarias', name: 'Facultad de Ciencias Veterinarias', acronym: 'FCV', dean: 'Prof. Dra. Viviana María Ríos Morínigo', website: 'www.vet.una.py', color: 'bg-teal-700' },
  { id: 'arquitectura', name: 'Facultad de Arquitectura, Diseño y Arte', acronym: 'FADA', dean: 'Prof. Arq. José Gregorio Insfrán', website: 'www.arq.una.py', color: 'bg-orange-600' },
  { id: 'politecnica', name: 'Facultad Politécnica', acronym: 'FP-UNA', dean: 'Prof. Silvia Teresa Leiva León', website: 'www.pol.una.py', color: 'bg-blue-600' },
  { id: 'exactas', name: 'Facultad de Ciencias Exactas y Naturales', acronym: 'FACEN', dean: 'Prof. Lic. Constantino Nicolás Güefos Kapsalis', website: 'www.facen.una.py', color: 'bg-indigo-600' },
  { id: 'enfermeria', name: 'Facultad de Enfermería y Obstetricia', acronym: 'FENOB', dean: 'Prof. Mst. María Isabel Rodríguez Vda. de Riveros', website: 'www.fenob.una.py', color: 'bg-rose-600' },
  { id: 'sociales', name: 'Facultad de Ciencias Sociales', acronym: 'FACSO', dean: 'Prof. Lic. Ada Concepción Vera Rojas', website: 'www.facso.una.py', color: 'bg-slate-600' },
];

// Common constants
const ADM_DERECHO_REQS = ['Fotocopia de título de Bachiller', 'Certificado de Estudios Original', 'Fotocopia de Cédula', 'Fotos tipo carnet', 'Formulario de Inscripción'];
const ADM_DERECHO_EXAMS = ['Comunicación y Redacción Castellana', 'Historia del Paraguay', 'Historia de las Instituciones Jurídicas', 'Introducción a las Ciencias Jurídicas'];
const ADM_MEDICINA_EXAMS = ['Biología', 'Química', 'Ciencias Exactas (Matemática y Física)', 'Lenguaje y Comunicación'];
const ADM_INGENIERIA_EXAMS = ['Matemática (Aritmética, Álgebra, Geometría, Trigonometría)', 'Física'];
const ADM_ECONOMIA_EXAMS = ['Matemática', 'Castellano', 'Introducción a la Contabilidad'];
const ADM_QUIMICA_EXAMS = ['Química', 'Matemática', 'Física'];
const ADM_FILOSOFIA_EXAMS = ['Psicología', 'Historia del Paraguay', 'Lengua Española', 'Matemática', 'Filosofía'];
const ADM_AGRARIAS_EXAMS = ['Química General', 'Comunicación', 'Física General', 'Biología', 'Matemática'];
const ADM_POLITECNICA_EXAMS = ['Matemática', 'Física', 'Castellano', 'Historia y Geografía del Paraguay'];

export const careers: Career[] = [
  // --- DERECHO (3) ---
  {
    id: 'der-01',
    name: 'Derecho',
    faculty: 'Facultad de Derecho y Ciencias Sociales',
    duration: '12 semestres',
    hours: 3818,
    modality: [Modality.Presencial],
    locations: ['Asunción', 'San Estanislao', 'Caacupé', 'Quiindy', 'Pedro Juan Caballero', 'San Juan Bautista', 'Coronel Oviedo', 'Benjamín Aceval'],
    description: 'Formación integral en ciencias jurídicas con énfasis en la justicia, democracia y derechos fundamentales.',
    profile: ['Conocimiento de normas positivas.', 'Interpretación y elaboración de normas jurídicas.', 'Actitud crítica e innovadora.'],
    shifts: ['Mañana', 'Tarde', 'Noche'],
    admissionCalendar: 'Noviembre a Enero (Inscripción)',
    admissionRequirements: ADM_DERECHO_REQS,
    admissionExams: ADM_DERECHO_EXAMS,
    contactEmail: 'informes@der.una.py',
    website: 'https://www.der.una.py',
    tags: ['leyes', 'abogado', 'justicia', 'sociales']
  },
  {
    id: 'der-02',
    name: 'Notariado',
    faculty: 'Facultad de Derecho y Ciencias Sociales',
    duration: '8 semestres',
    hours: 2720,
    modality: [Modality.Presencial],
    locations: ['Asunción'],
    description: 'Formación especializada para la función notarial y la seguridad jurídica.',
    profile: ['Conocimiento del ordenamiento jurídico notarial.', 'Capacidad para dar autenticidad a documentos.'],
    shifts: ['Noche'],
    admissionCalendar: 'Noviembre a Enero (Inscripción)',
    admissionRequirements: ADM_DERECHO_REQS,
    admissionExams: ['Introducción al Derecho Notarial', 'Hechos y Actos Jurídicos', 'Metodología'],
    contactEmail: 'dacad@der.una.py',
    website: 'https://www.der.una.py',
    tags: ['escribanía', 'leyes', 'documentos']
  },
  {
    id: 'der-03',
    name: 'Ciencias Políticas',
    faculty: 'Facultad de Derecho y Ciencias Sociales',
    duration: '8 semestres',
    hours: 3672,
    modality: [Modality.Presencial],
    locations: ['Asunción (Edificio Histórico)'],
    description: 'Análisis de procesos políticos, políticas públicas y relaciones de poder.',
    profile: ['Formar analistas y evaluadores de políticas sociales.', 'Liderazgo en organizaciones políticas.'],
    shifts: ['Noche'],
    admissionCalendar: 'Diciembre a Febrero (Inscripción)',
    admissionRequirements: ADM_DERECHO_REQS,
    admissionExams: ['Historia Social Latinoamericana', 'Idioma Guaraní', 'Sociología del Trabajo'],
    contactEmail: 'admin_esc@der.una.py',
    website: 'https://www.der.una.py',
    tags: ['política', 'gobierno', 'estado']
  },

  // --- MEDICINA (3) ---
  {
    id: 'med-01',
    name: 'Medicina y Cirugía',
    faculty: 'Facultad de Ciencias Médicas',
    duration: '6 años',
    hours: 10720,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo', 'Santa Rosa del Aguaray'],
    description: 'Formación médica de excelencia con enfoque humanista y científico.',
    profile: ['Atención integral del proceso salud-enfermedad.', 'Diagnóstico, tratamiento y rehabilitación.'],
    shifts: ['Mañana', 'Tarde'],
    admissionCalendar: 'Octubre a Enero (Inscripción)',
    admissionRequirements: ['Certificado de Estudios', 'Título de Bachiller', 'Cédula de Identidad'],
    admissionExams: ADM_MEDICINA_EXAMS,
    contactEmail: 'fcm@med.una.py',
    website: 'https://med.una.py',
    tags: ['salud', 'doctor', 'hospital', 'clínica']
  },
  {
    id: 'med-02',
    name: 'Kinesiología y Fisioterapia',
    faculty: 'Facultad de Ciencias Médicas',
    duration: '5 años',
    hours: 8102,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Profesionales capacitados en la rehabilitación física y el movimiento humano.',
    profile: ['Aplicar agentes kinefilácticos.', 'Rehabilitación músculo-esquelética.'],
    shifts: ['Completo'],
    admissionCalendar: 'Octubre a Enero (Inscripción)',
    admissionRequirements: ['Certificado de Estudios', 'Título de Bachiller', 'Cédula de Identidad'],
    admissionExams: ADM_MEDICINA_EXAMS,
    contactEmail: 'kinesiologia@fcmuna.edu.py',
    website: 'https://med.una.py',
    tags: ['salud', 'rehabilitación', 'física']
  },
  {
    id: 'med-03',
    name: 'Instrumentación y Área Quirúrgica',
    faculty: 'Facultad de Ciencias Médicas',
    duration: '4 años',
    hours: 3202,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Formación técnica y científica para el apoyo en procedimientos quirúrgicos.',
    profile: ['Profesional con formación integral científica y ética en el área quirúrgica.'],
    shifts: ['Mañana', 'Tarde'],
    admissionCalendar: 'Enero (Inscripción Propedéutico)',
    admissionRequirements: ['Formulario web', 'Cédula', 'Certificado de Estudios'],
    admissionExams: ['Biología', 'Ciencias Exactas', 'Lenguaje', 'RSU'],
    contactEmail: 'fcm@med.una.py',
    website: 'https://med.una.py',
    tags: ['salud', 'quirófano', 'cirugía']
  },

  // --- INGENIERIA (7) ---
  {
    id: 'ing-01',
    name: 'Ingeniería Civil',
    faculty: 'Facultad de Ingeniería',
    duration: '10 semestres',
    hours: 4882,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo', 'Ayolas'],
    description: 'Diseño y construcción de infraestructuras, obras viales, hidráulicas y estructurales.',
    profile: ['Proyectar y construir obras civiles.', 'Estudios de factibilidad.'],
    shifts: ['Mañana', 'Tarde'],
    admissionCalendar: 'Noviembre a Enero (Inscripción CPI)',
    admissionRequirements: ['Título de Bachiller', 'Certificado de Estudios'],
    admissionExams: ADM_INGENIERIA_EXAMS,
    contactEmail: 'secretaria@ing.una.py',
    website: 'https://www.ing.una.py',
    tags: ['construcción', 'estructuras', 'vial']
  },
  {
    id: 'ing-02',
    name: 'Ingeniería Industrial',
    faculty: 'Facultad de Ingeniería',
    duration: '10 semestres',
    hours: 4797,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Optimización de procesos productivos y gestión industrial.',
    profile: ['Proyectar sistemas de producción.', 'Planificar y controlar procesos.'],
    shifts: ['Mañana', 'Tarde', 'Noche'],
    admissionCalendar: 'Noviembre a Enero (Inscripción CPI)',
    admissionRequirements: ['Título de Bachiller', 'Certificado de Estudios'],
    admissionExams: ADM_INGENIERIA_EXAMS,
    contactEmail: 'secretaria@ing.una.py',
    website: 'https://www.ing.una.py',
    tags: ['industria', 'procesos', 'gestión']
  },
  {
    id: 'ing-03',
    name: 'Ingeniería Electromecánica',
    faculty: 'Facultad de Ingeniería',
    duration: '10 semestres',
    hours: 4763,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo', 'Ayolas'],
    description: 'Integración de sistemas eléctricos y mecánicos.',
    profile: ['Operar y mantener obras electromecánicas.', 'Proyectar obras con máquinas y energía.'],
    shifts: ['Mañana', 'Tarde'],
    admissionCalendar: 'Noviembre a Enero (Inscripción CPI)',
    admissionRequirements: ['Título de Bachiller', 'Certificado de Estudios'],
    admissionExams: ADM_INGENIERIA_EXAMS,
    contactEmail: 'secretaria@ing.una.py',
    website: 'https://www.ing.una.py',
    tags: ['electricidad', 'mecánica', 'energía']
  },
  {
    id: 'ing-04',
    name: 'Ingeniería Electrónica',
    faculty: 'Facultad de Ingeniería',
    duration: '10 semestres',
    hours: 4329,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo', 'Luque'],
    description: 'Sistemas electrónicos, telecomunicaciones y control.',
    profile: ['Desarrollar proyectos de sistemas electrónicos.', 'Automatización y control.'],
    shifts: ['Mañana', 'Tarde', 'Noche'],
    admissionCalendar: 'Noviembre a Enero (Inscripción CPI)',
    admissionRequirements: ['Título de Bachiller', 'Certificado de Estudios'],
    admissionExams: ADM_INGENIERIA_EXAMS,
    contactEmail: 'secretaria@ing.una.py',
    website: 'https://www.ing.una.py',
    tags: ['electrónica', 'tecnología', 'sistemas']
  },
  {
    id: 'ing-05',
    name: 'Ingeniería Geográfica y Ambiental',
    faculty: 'Facultad de Ingeniería',
    duration: '10 semestres',
    hours: 5001,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Gestión del territorio y recursos naturales con enfoque ambiental.',
    profile: ['Levantamientos territoriales.', 'Gestión ambiental.'],
    shifts: ['Mañana', 'Tarde', 'Noche'],
    admissionCalendar: 'Noviembre a Enero (Inscripción CPI)',
    admissionRequirements: ['Título de Bachiller', 'Certificado de Estudios'],
    admissionExams: ADM_INGENIERIA_EXAMS,
    contactEmail: 'secretaria@ing.una.py',
    website: 'https://www.ing.una.py',
    tags: ['ambiente', 'geografía', 'territorio']
  },
  {
    id: 'ing-06',
    name: 'Ingeniería Mecánica',
    faculty: 'Facultad de Ingeniería',
    duration: '10 semestres',
    hours: 4848,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Diseño y mantenimiento de sistemas mecánicos y térmicos.',
    profile: ['Desarrollar soluciones en ingeniería mecánica.', 'Mantenimiento industrial.'],
    shifts: ['Mañana', 'Tarde', 'Noche'],
    admissionCalendar: 'Noviembre a Enero (Inscripción CPI)',
    admissionRequirements: ['Título de Bachiller', 'Certificado de Estudios'],
    admissionExams: ADM_INGENIERIA_EXAMS,
    contactEmail: 'secretaria@ing.una.py',
    website: 'https://www.ing.una.py',
    tags: ['mecánica', 'máquinas', 'motores']
  },
  {
    id: 'ing-07',
    name: 'Ingeniería Mecatrónica',
    faculty: 'Facultad de Ingeniería',
    duration: '10 semestres',
    hours: 4516,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo', 'Luque'],
    description: 'Sinergia de mecánica, electrónica e informática para automatización.',
    profile: ['Diseñar sistemas mecatrónicos.', 'Automatizar procesos industriales.'],
    shifts: ['Mañana', 'Tarde', 'Noche'],
    admissionCalendar: 'Noviembre a Enero (Inscripción CPI)',
    admissionRequirements: ['Título de Bachiller', 'Certificado de Estudios'],
    admissionExams: ADM_INGENIERIA_EXAMS,
    contactEmail: 'secretaria@ing.una.py',
    website: 'https://www.ing.una.py',
    tags: ['robotica', 'automatización', 'tecnología']
  },

  // --- ECONOMICAS (3) ---
  {
    id: 'eco-01',
    name: 'Economía',
    faculty: 'Facultad de Ciencias Económicas',
    duration: '10 semestres',
    hours: 3796,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Estudio de la asignación de recursos, mercados y políticas económicas.',
    profile: ['Proponer estrategias de desarrollo económico.', 'Análisis macro y microeconómico.'],
    shifts: ['Mañana', 'Tarde', 'Noche'],
    admissionCalendar: 'Octubre a Diciembre (Inscripción CPA)',
    admissionRequirements: ['Certificado de Estudios', 'Título de Bachiller', 'Cédula'],
    admissionExams: ADM_ECONOMIA_EXAMS,
    contactEmail: 'info@eco.una.py',
    website: 'https://www.eco.una.py',
    tags: ['economía', 'finanzas', 'política']
  },
  {
    id: 'eco-02',
    name: 'Administración',
    faculty: 'Facultad de Ciencias Económicas',
    duration: '10 semestres',
    hours: 3100,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo', 'Villa Hayes', 'Paraguarí', 'Coronel Oviedo', 'Villarrica', 'Caaguazú', 'San Estanislao', 'Caacupé'],
    description: 'Gestión eficiente de organizaciones y recursos empresariales.',
    profile: ['Dirigir y gestionar empresas.', 'Planificación estratégica.'],
    shifts: ['Mañana', 'Tarde', 'Noche'],
    admissionCalendar: 'Octubre a Diciembre (Inscripción CPA)',
    admissionRequirements: ['Certificado de Estudios', 'Título de Bachiller', 'Cédula'],
    admissionExams: ADM_ECONOMIA_EXAMS,
    contactEmail: 'info@eco.una.py',
    website: 'https://www.eco.una.py',
    tags: ['administración', 'negocios', 'gestión']
  },
  {
    id: 'eco-03',
    name: 'Contaduría Pública',
    faculty: 'Facultad de Ciencias Económicas',
    duration: '10 semestres',
    hours: 3320,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo', 'Paraguarí', 'Villa Hayes', 'Villarrica', 'Caacupé', 'San Pedro', 'Cnel. Oviedo', 'San Estanislao', 'Caaguazú'],
    description: 'Sistemas de información contable, auditoría y tributación.',
    profile: ['Elaborar estados financieros.', 'Auditoría y asesoría fiscal.'],
    shifts: ['Mañana', 'Tarde', 'Noche'],
    admissionCalendar: 'Octubre a Diciembre (Inscripción CPA)',
    admissionRequirements: ['Certificado de Estudios', 'Título de Bachiller', 'Cédula'],
    admissionExams: ADM_ECONOMIA_EXAMS,
    contactEmail: 'info@eco.una.py',
    website: 'https://www.eco.una.py',
    tags: ['contabilidad', 'impuestos', 'finanzas']
  },

  // --- ODONTOLOGIA (1) ---
  {
    id: 'odo-01',
    name: 'Odontología',
    faculty: 'Facultad de Odontología',
    duration: '5 años',
    hours: 5999,
    modality: [Modality.Presencial],
    locations: ['Asunción'],
    description: 'Prevención, diagnóstico y tratamiento de la salud bucal.',
    profile: ['Diagnóstico y tratamiento de patologías bucales.', 'Rehabilitación oral.'],
    shifts: ['Completo', 'Mañana', 'Tarde', 'Noche'],
    admissionCalendar: 'Marzo a Enero (Curso Extensivo)',
    admissionRequirements: ['Cédula de Identidad', 'Certificado de Estudios', 'Título de Bachiller'],
    admissionExams: ['Biología', 'Matemática', 'Comunicación', 'Química', 'Física'],
    contactEmail: 'fo@odo.una.py',
    website: 'https://odo.una.py',
    tags: ['dientes', 'salud', 'boca']
  },

  // --- QUIMICAS (7) ---
  {
    id: 'qui-01',
    name: 'Farmacia',
    faculty: 'Facultad de Ciencias Químicas',
    duration: '11 semestres',
    hours: 4905,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Ciencia del medicamento, producción y atención farmacéutica.',
    profile: ['Diseño y control de medicamentos.', 'Atención farmacéutica.'],
    shifts: ['Completo'],
    admissionCalendar: 'Septiembre a Octubre (Pre Admisión)',
    admissionRequirements: ['Título de Bachiller', 'Certificado de Estudios', 'Cédula'],
    admissionExams: ADM_QUIMICA_EXAMS,
    contactEmail: 'info@qui.una.py',
    website: 'https://www.qui.una.py',
    tags: ['farmacia', 'medicamentos', 'salud']
  },
  {
    id: 'qui-02',
    name: 'Bioquímica',
    faculty: 'Facultad de Ciencias Químicas',
    duration: '11 semestres',
    hours: 5110,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Análisis clínicos y biológicos para diagnóstico y tratamiento.',
    profile: ['Análisis clínicos y toxicológicos.', 'Investigación biomédica.'],
    shifts: ['Mañana', 'Tarde'],
    admissionCalendar: 'Septiembre a Octubre (Pre Admisión)',
    admissionRequirements: ['Título de Bachiller', 'Certificado de Estudios', 'Cédula'],
    admissionExams: ADM_QUIMICA_EXAMS,
    contactEmail: 'info@qui.una.py',
    website: 'https://www.qui.una.py',
    tags: ['laboratorio', 'análisis', 'salud']
  },
  {
    id: 'qui-03',
    name: 'Ingeniería Química',
    faculty: 'Facultad de Ciencias Químicas',
    duration: '11 semestres',
    hours: 4895,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Procesos industriales de transformación química y física.',
    profile: ['Diseño de procesos industriales.', 'Gestión de plantas químicas.'],
    shifts: ['Completo'],
    admissionCalendar: 'Septiembre a Octubre (Pre Admisión)',
    admissionRequirements: ['Título de Bachiller', 'Certificado de Estudios', 'Cédula'],
    admissionExams: ADM_QUIMICA_EXAMS,
    contactEmail: 'info@qui.una.py',
    website: 'https://www.qui.una.py',
    tags: ['industria', 'procesos', 'química']
  },
  {
    id: 'qui-04',
    name: 'Química Industrial',
    faculty: 'Facultad de Ciencias Químicas',
    duration: '9 semestres',
    hours: 3720,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Control y optimización de procesos industriales químicos.',
    profile: ['Control de calidad industrial.', 'Optimización de procesos.'],
    shifts: ['Completo'],
    admissionCalendar: 'Septiembre a Octubre (Pre Admisión)',
    admissionRequirements: ['Título de Bachiller', 'Certificado de Estudios', 'Cédula'],
    admissionExams: ADM_QUIMICA_EXAMS,
    contactEmail: 'info@qui.una.py',
    website: 'https://www.qui.una.py',
    tags: ['industria', 'calidad', 'química']
  },
  {
    id: 'qui-05',
    name: 'Ciencia y Tecnología de Alimentos',
    faculty: 'Facultad de Ciencias Químicas',
    duration: '9 semestres',
    hours: 3770,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo', 'Guajayvi'],
    description: 'Producción, conservación y control de calidad de alimentos.',
    profile: ['Gestión de calidad alimentaria.', 'Desarrollo de productos.'],
    shifts: ['Completo'],
    admissionCalendar: 'Septiembre a Octubre (Pre Admisión)',
    admissionRequirements: ['Título de Bachiller', 'Certificado de Estudios', 'Cédula'],
    admissionExams: ADM_QUIMICA_EXAMS,
    contactEmail: 'info@qui.una.py',
    website: 'https://www.qui.una.py',
    tags: ['alimentos', 'tecnología', 'calidad']
  },
  {
    id: 'qui-06',
    name: 'Ingeniería de Alimentos',
    faculty: 'Facultad de Ciencias Químicas',
    duration: '11 semestres',
    hours: 4910,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Diseño de procesos y equipos para la industria alimentaria.',
    profile: ['Diseño de plantas de alimentos.', 'Procesamiento industrial.'],
    shifts: ['Completo'],
    admissionCalendar: 'Septiembre a Octubre (Pre Admisión)',
    admissionRequirements: ['Título de Bachiller', 'Certificado de Estudios', 'Cédula'],
    admissionExams: ADM_QUIMICA_EXAMS,
    contactEmail: 'info@qui.una.py',
    website: 'https://www.qui.una.py',
    tags: ['ingeniería', 'alimentos', 'industria']
  },
  {
    id: 'qui-07',
    name: 'Nutrición',
    faculty: 'Facultad de Ciencias Químicas',
    duration: '10 semestres',
    hours: 4455,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Ciencia de la alimentación y su relación con la salud.',
    profile: ['Atención dietética y nutricional.', 'Salud pública.'],
    shifts: ['Completo'],
    admissionCalendar: 'Septiembre a Octubre (Pre Admisión)',
    admissionRequirements: ['Título de Bachiller', 'Certificado de Estudios', 'Cédula'],
    admissionExams: ADM_QUIMICA_EXAMS,
    contactEmail: 'info@qui.una.py',
    website: 'https://www.qui.una.py',
    tags: ['salud', 'dieta', 'alimentación']
  },

  // --- FILOSOFIA (11) ---
  {
    id: 'fil-01',
    name: 'Filosofía',
    faculty: 'Facultad de Filosofía',
    duration: '4 años',
    hours: 2784,
    modality: [Modality.Presencial],
    locations: ['Asunción'],
    description: 'Reflexión crítica sobre el pensamiento, la existencia y la ética.',
    profile: ['Pensamiento crítico.', 'Docencia e investigación filosófica.'],
    shifts: ['Noche'],
    admissionCalendar: 'Noviembre a Febrero (Cursillo)',
    admissionRequirements: ['Bachiller', 'Certificado Estudios', 'Cédula'],
    admissionExams: ADM_FILOSOFIA_EXAMS,
    contactEmail: 'secacademica@fil.una.py',
    website: 'https://www.fil.una.py',
    tags: ['pensamiento', 'humanidades', 'ética']
  },
  {
    id: 'fil-02',
    name: 'Letras',
    faculty: 'Facultad de Filosofía',
    duration: '4 años',
    hours: 3820,
    modality: [Modality.Presencial],
    locations: ['Asunción', 'Caacupé', 'San Estanislao'],
    description: 'Estudio de la lengua y la literatura, análisis y producción de textos.',
    profile: ['Conocimiento lingüístico y literario.', 'Docencia e investigación.'],
    shifts: ['Noche'],
    admissionCalendar: 'Noviembre a Febrero (Cursillo)',
    admissionRequirements: ['Bachiller', 'Certificado Estudios', 'Cédula'],
    admissionExams: ADM_FILOSOFIA_EXAMS,
    contactEmail: 'secacademica@fil.una.py',
    website: 'https://www.fil.una.py',
    tags: ['lengua', 'literatura', 'escritura']
  },
  {
    id: 'fil-03',
    name: 'Historia',
    faculty: 'Facultad de Filosofía',
    duration: '4 años',
    hours: 3442,
    modality: [Modality.Presencial],
    locations: ['Asunción'],
    description: 'Estudio de los procesos históricos nacionales y universales.',
    profile: ['Investigación histórica.', 'Docencia en historia.'],
    shifts: ['Noche'],
    admissionCalendar: 'Noviembre a Febrero (Cursillo)',
    admissionRequirements: ['Bachiller', 'Certificado Estudios', 'Cédula'],
    admissionExams: ADM_FILOSOFIA_EXAMS,
    contactEmail: 'secacademica@fil.una.py',
    website: 'https://www.fil.una.py',
    tags: ['pasado', 'sociedad', 'investigación']
  },
  {
    id: 'fil-04',
    name: 'Psicología',
    faculty: 'Facultad de Filosofía',
    duration: '5 años',
    hours: 4560,
    modality: [Modality.Presencial],
    locations: ['Asunción', 'Caacupé', 'San Juan Bautista', 'San Pedro', 'Caaguazú', 'Paraguarí', 'San Estanislao'],
    description: 'Estudio del comportamiento humano y procesos mentales.',
    profile: ['Evaluación y diagnóstico psicológico.', 'Intervención en salud mental.'],
    shifts: ['Tarde', 'Noche'],
    admissionCalendar: 'Noviembre a Febrero (Cursillo)',
    admissionRequirements: ['Bachiller', 'Certificado Estudios', 'Cédula'],
    admissionExams: ADM_FILOSOFIA_EXAMS,
    contactEmail: 'secacademica@fil.una.py',
    website: 'https://www.fil.una.py',
    tags: ['salud mental', 'comportamiento', 'terapia']
  },
  {
    id: 'fil-05',
    name: 'Ciencias de la Comunicación',
    faculty: 'Facultad de Filosofía',
    duration: '4 años',
    hours: 3400,
    modality: [Modality.Presencial],
    locations: ['Asunción', 'San Juan Bautista'],
    description: 'Periodismo, comunicación institucional y producción de medios.',
    profile: ['Producción de noticias.', 'Gestión de comunicación.'],
    shifts: ['Tarde', 'Noche'],
    admissionCalendar: 'Noviembre a Febrero (Cursillo)',
    admissionRequirements: ['Bachiller', 'Certificado Estudios', 'Cédula'],
    admissionExams: ADM_FILOSOFIA_EXAMS,
    contactEmail: 'secacademica@fil.una.py',
    website: 'https://www.fil.una.py',
    tags: ['periodismo', 'medios', 'radio', 'tv']
  },
  {
    id: 'fil-06',
    name: 'Ciencias de la Educación',
    faculty: 'Facultad de Filosofía',
    duration: '4 años',
    hours: 4051,
    modality: [Modality.Presencial],
    locations: ['Asunción', 'Caacupé', 'San Juan Bautista', 'San Pedro', 'Caaguazú', 'Paraguarí', 'San Estanislao', 'Villarrica'],
    description: 'Formación de profesionales para la gestión y práctica educativa.',
    profile: ['Gestión educativa.', 'Diseño curricular y docencia.'],
    shifts: ['Noche'],
    admissionCalendar: 'Noviembre a Febrero (Cursillo)',
    admissionRequirements: ['Bachiller', 'Certificado Estudios', 'Cédula'],
    admissionExams: ADM_FILOSOFIA_EXAMS,
    contactEmail: 'secacademica@fil.una.py',
    website: 'https://www.fil.una.py',
    tags: ['enseñanza', 'pedagogía', 'escuela']
  },
  {
    id: 'fil-07',
    name: 'Licenciatura en Educación Inicial',
    faculty: 'Facultad de Filosofía',
    duration: '4 años',
    hours: 3600,
    modality: [Modality.Presencial],
    locations: ['Asunción'],
    description: 'Atención educativa a la primera infancia.',
    profile: ['Docencia en nivel inicial.', 'Gestión de centros infantiles.'],
    shifts: ['Mañana'],
    admissionCalendar: 'Noviembre a Febrero (Cursillo)',
    admissionRequirements: ['Bachiller', 'Certificado Estudios', 'Cédula'],
    admissionExams: ADM_FILOSOFIA_EXAMS,
    contactEmail: 'secacademica@fil.una.py',
    website: 'https://www.fil.una.py',
    tags: ['niños', 'jardín', 'enseñanza']
  },
  {
    id: 'fil-08',
    name: 'Lengua Inglesa',
    faculty: 'Facultad de Filosofía',
    duration: '4 años',
    hours: 2880,
    modality: [Modality.Presencial],
    locations: ['Asunción (ISL)'],
    description: 'Estudio y enseñanza del idioma inglés.',
    profile: ['Docencia del inglés.', 'Traducción básica.'],
    shifts: ['Noche'],
    admissionCalendar: 'Febrero a Marzo (Cursillo ISL)',
    admissionRequirements: ['Bachiller', 'Certificado Estudios', 'Cédula'],
    admissionExams: ['Comprensión Oral', 'Comprensión Escrita', 'Expresión Oral', 'Expresión Escrita (Castellano)'],
    contactEmail: 'isl-direccion@fil.una.py',
    website: 'https://www.fil.una.py',
    tags: ['idiomas', 'english', 'docencia']
  },
  {
    id: 'fil-09',
    name: 'Lengua Francesa',
    faculty: 'Facultad de Filosofía',
    duration: '4 años',
    hours: 2560,
    modality: [Modality.Presencial],
    locations: ['Asunción (ISL)'],
    description: 'Estudio y enseñanza de la lengua y cultura francesa.',
    profile: ['Dominio del francés.', 'Docencia y traducción.'],
    shifts: ['Noche'],
    admissionCalendar: 'Febrero a Marzo (Cursillo ISL)',
    admissionRequirements: ['Bachiller', 'Certificado Estudios', 'Cédula'],
    admissionExams: ['Comprensión Oral', 'Comprensión Escrita', 'Expresión Oral', 'Expresión Escrita (Castellano)'],
    contactEmail: 'isl-direccion@fil.una.py',
    website: 'https://www.fil.una.py',
    tags: ['idiomas', 'francés', 'cultura']
  },
  {
    id: 'fil-10',
    name: 'Lengua Guaraní',
    faculty: 'Facultad de Filosofía',
    duration: '4 años',
    hours: 3040,
    modality: [Modality.Presencial],
    locations: ['Asunción (ISL)'],
    description: 'Estudio, promoción y enseñanza de la lengua guaraní.',
    profile: ['Docencia e investigación en guaraní.', 'Promoción cultural.'],
    shifts: ['Noche'],
    admissionCalendar: 'Febrero a Marzo (Cursillo ISL)',
    admissionRequirements: ['Bachiller', 'Certificado Estudios', 'Cédula'],
    admissionExams: ['Comprensión Oral', 'Comprensión Escrita', 'Expresión Oral', 'Expresión Escrita (Castellano)'],
    contactEmail: 'isl-direccion@fil.una.py',
    website: 'https://www.fil.una.py',
    tags: ['idiomas', 'guaraní', 'cultura']
  },
  {
    id: 'fil-11',
    name: 'Lengua Alemana',
    faculty: 'Facultad de Filosofía',
    duration: '4 años',
    hours: 2016,
    modality: [Modality.Presencial],
    locations: ['Asunción (ISL)'],
    description: 'Estudio y enseñanza del idioma alemán.',
    profile: ['Docencia del alemán.', 'Traducción y cultura.'],
    shifts: ['Noche'],
    admissionCalendar: 'Febrero a Marzo (Cursillo ISL)',
    admissionRequirements: ['Bachiller', 'Certificado Estudios', 'Cédula'],
    admissionExams: ['Comprensión Oral', 'Comprensión Escrita', 'Expresión Oral', 'Expresión Escrita (Castellano)'],
    contactEmail: 'isl-direccion@fil.una.py',
    website: 'https://www.fil.una.py',
    tags: ['idiomas', 'alemán', 'europa']
  },
  {
    id: 'fil-12',
    name: 'Lengua Portuguesa',
    faculty: 'Facultad de Filosofía',
    duration: '4 años',
    hours: 2760,
    modality: [Modality.Presencial],
    locations: ['Asunción (ISL)'],
    description: 'Estudio y enseñanza del idioma portugués.',
    profile: ['Docencia del portugués.', 'Traducción y cultura brasileña.'],
    shifts: ['Noche'],
    admissionCalendar: 'Febrero a Marzo (Cursillo ISL)',
    admissionRequirements: ['Bachiller', 'Certificado Estudios', 'Cédula'],
    admissionExams: ['Comprensión Oral', 'Comprensión Escrita', 'Expresión Oral', 'Expresión Escrita (Castellano)'],
    contactEmail: 'isl-direccion@fil.una.py',
    website: 'https://www.fil.una.py',
    tags: ['idiomas', 'portugués', 'brasil']
  },

  // --- AGRARIAS (6) ---
  {
    id: 'agr-01',
    name: 'Ingeniería Agronómica',
    faculty: 'Facultad de Ciencias Agrarias',
    duration: '9 semestres',
    hours: 3465,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo', 'Pedro Juan Caballero', 'San Pedro', 'Caazapá', 'Santa Rosa (Misiones)'],
    description: 'Gestión de sistemas de producción agrícola y desarrollo rural.',
    profile: ['Manejo de cultivos.', 'Producción sostenible.'],
    shifts: ['Mañana', 'Tarde'],
    admissionCalendar: 'Noviembre a Diciembre (Inscripción)',
    admissionRequirements: ['Título de Bachiller', 'Cédula de Identidad', 'Solicitud'],
    admissionExams: ADM_AGRARIAS_EXAMS,
    contactEmail: 'secretariafca@agr.una.py',
    website: 'https://www.agr.una.py',
    tags: ['campo', 'agro', 'cultivos']
  },
  {
    id: 'agr-02',
    name: 'Ingeniería Forestal',
    faculty: 'Facultad de Ciencias Agrarias',
    duration: '9 semestres',
    hours: 3570,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Manejo sostenible de bosques y recursos forestales.',
    profile: ['Gestión forestal.', 'Conservación de recursos.'],
    shifts: ['Mañana', 'Tarde'],
    admissionCalendar: 'Noviembre a Diciembre (Inscripción)',
    admissionRequirements: ['Título de Bachiller', 'Cédula de Identidad', 'Solicitud'],
    admissionExams: ADM_AGRARIAS_EXAMS,
    contactEmail: 'secretariafca@agr.una.py',
    website: 'https://www.agr.una.py',
    tags: ['bosques', 'árboles', 'ambiente']
  },
  {
    id: 'agr-03',
    name: 'Ingeniería en Ecología Humana',
    faculty: 'Facultad de Ciencias Agrarias',
    duration: '9 semestres',
    hours: 3555,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Mejoramiento de la calidad de vida y desarrollo social sostenible.',
    profile: ['Desarrollo comunitario.', 'Gestión social y ambiental.'],
    shifts: ['Mañana', 'Tarde'],
    admissionCalendar: 'Noviembre a Diciembre (Inscripción)',
    admissionRequirements: ['Título de Bachiller', 'Cédula de Identidad', 'Solicitud'],
    admissionExams: ADM_AGRARIAS_EXAMS,
    contactEmail: 'secretariafca@agr.una.py',
    website: 'https://www.agr.una.py',
    tags: ['sociedad', 'ambiente', 'desarrollo']
  },
  {
    id: 'agr-04',
    name: 'Ingeniería Ambiental',
    faculty: 'Facultad de Ciencias Agrarias',
    duration: '9 semestres',
    hours: 3525,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Soluciones a problemas ambientales y gestión de recursos naturales.',
    profile: ['Evaluación de impacto ambiental.', 'Gestión de residuos.'],
    shifts: ['Tarde', 'Noche'],
    admissionCalendar: 'Noviembre a Diciembre (Inscripción)',
    admissionRequirements: ['Título de Bachiller', 'Cédula de Identidad', 'Solicitud'],
    admissionExams: ADM_AGRARIAS_EXAMS,
    contactEmail: 'secretariafca@agr.una.py',
    website: 'https://www.agr.una.py',
    tags: ['ambiente', 'ecología', 'sostenibilidad']
  },
  {
    id: 'agr-05',
    name: 'Ingeniería Agroalimentaria',
    faculty: 'Facultad de Ciencias Agrarias',
    duration: '9 semestres',
    hours: 3555,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Procesamiento e industrialización de productos agropecuarios.',
    profile: ['Industria de alimentos.', 'Calidad agroalimentaria.'],
    shifts: ['Mañana', 'Tarde'],
    admissionCalendar: 'Noviembre a Diciembre (Inscripción)',
    admissionRequirements: ['Título de Bachiller', 'Cédula de Identidad', 'Solicitud'],
    admissionExams: ADM_AGRARIAS_EXAMS,
    contactEmail: 'secretariafca@agr.una.py',
    website: 'https://www.agr.una.py',
    tags: ['alimentos', 'industria', 'procesos']
  },
  {
    id: 'agr-06',
    name: 'Licenciatura en Administración Agropecuaria',
    faculty: 'Facultad de Ciencias Agrarias',
    duration: '9 semestres',
    hours: 3000,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo', 'Pedro Juan Caballero', 'San Pedro', 'Santa Rosa', 'Caazapá', 'Neuland (Boquerón)'],
    description: 'Gestión y administración de empresas agropecuarias.',
    profile: ['Administración rural.', 'Agronegocios.'],
    shifts: ['Noche'],
    admissionCalendar: 'Noviembre a Diciembre (Inscripción)',
    admissionRequirements: ['Título de Bachiller', 'Cédula de Identidad', 'Solicitud'],
    admissionExams: ['Introducción a la Economía', 'Introducción a la Administración', 'Comunicación', 'Matemática', 'Biología'],
    contactEmail: 'secretariafca@agr.una.py',
    website: 'https://www.agr.una.py',
    tags: ['negocios', 'campo', 'administración']
  },

  // --- VETERINARIA (1) ---
  {
    id: 'vet-01',
    name: 'Ciencias Veterinarias',
    faculty: 'Facultad de Ciencias Veterinarias',
    duration: '6.5 años',
    hours: 5340,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo', 'Concepción', 'San Juan Bautista', 'Caazapá', 'San Estanislao'],
    description: 'Salud animal, producción pecuaria y salud pública.',
    profile: ['Clínica veterinaria.', 'Producción animal.', 'Salud pública.'],
    shifts: ['Mañana', 'Tarde'],
    admissionCalendar: 'Enero a Febrero (Inscripción)',
    admissionRequirements: ['Certificado de Estudios', 'Título de Bachiller', 'Cédula de Identidad', 'Antecedentes Policiales', 'Grupo Sanguíneo'],
    admissionExams: ['Biología', 'Matemática', 'Comunicación', 'Química', 'Física'],
    contactEmail: 'veterin@vet.una.py',
    website: 'https://www.vet.una.py',
    tags: ['animales', 'salud', 'campo']
  },

  // --- FADA (7) ---
  {
    id: 'fada-01',
    name: 'Arquitectura y Urbanismo',
    faculty: 'Facultad de Arquitectura, Diseño y Arte',
    duration: '11 semestres',
    hours: 3995,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Diseño de espacios habitables y planificación urbana.',
    profile: ['Proyecto arquitectónico.', 'Urbanismo.', 'Construcción.'],
    shifts: ['Tarde', 'Noche'],
    admissionCalendar: 'Febrero a Marzo (Nivelación)',
    admissionRequirements: ['Certificado de Estudios', 'Título de Bachiller', 'Certificado de Nacimiento'],
    admissionExams: ['Lógica Matemática', 'Lógica Física', 'Comunicación', 'Creatividad'],
    contactEmail: 'direccionarq@fada.una.py',
    website: 'https://www.arq.una.py',
    tags: ['diseño', 'construcción', 'ciudad']
  },
  {
    id: 'fada-02',
    name: 'Licenciatura en Artes Visuales',
    faculty: 'Facultad de Arquitectura, Diseño y Arte',
    duration: '8 semestres',
    hours: 3332,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Creación e investigación en artes plásticas y visuales.',
    profile: ['Artista visual.', 'Gestor cultural.', 'Investigador en arte.'],
    shifts: ['Tarde (Ciclo Básico)', 'Noche (Profesional)'],
    admissionCalendar: 'Noviembre a Diciembre (Inscripción)',
    admissionRequirements: ['Certificado de Estudios', 'Título de Bachiller', 'Certificado de Nacimiento'],
    admissionExams: ['Dibujo', 'Comprensión Lectora', 'Apreciación Visual'],
    contactEmail: 'infisa@fada.una.py',
    website: 'https://www.arq.una.py',
    tags: ['arte', 'pintura', 'cultura']
  },
  {
    id: 'fada-03',
    name: 'Diseño de Indumentaria Escénica y Urbana',
    faculty: 'Facultad de Arquitectura, Diseño y Arte',
    duration: '8 semestres',
    hours: 3502,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Diseño de moda y vestuario para espectáculos.',
    profile: ['Diseño de moda.', 'Vestuario escénico.'],
    shifts: ['Tarde (Ciclo Básico)', 'Noche (Profesional)'],
    admissionCalendar: 'Noviembre a Diciembre (Inscripción)',
    admissionRequirements: ['Certificado de Estudios', 'Título de Bachiller', 'Certificado de Nacimiento'],
    admissionExams: ['Dibujo', 'Comprensión Lectora', 'Apreciación Visual'],
    contactEmail: 'infisa@fada.una.py',
    website: 'https://www.arq.una.py',
    tags: ['moda', 'ropa', 'diseño']
  },
  {
    id: 'fada-04',
    name: 'Diseño Industrial',
    faculty: 'Facultad de Arquitectura, Diseño y Arte',
    duration: '8 semestres',
    hours: 3009,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Diseño de productos y diseño gráfico.',
    profile: ['Diseño de productos.', 'Diseño gráfico.'],
    shifts: ['Mañana', 'Tarde', 'Noche'],
    admissionCalendar: 'Febrero a Marzo (Nivelación)',
    admissionRequirements: ['Certificado de Estudios', 'Título de Bachiller', 'Certificado de Nacimiento'],
    admissionExams: ['Lógica Matemática', 'Lógica Física', 'Comunicación', 'Creatividad'],
    contactEmail: 'oottaviano478@fada.una.py',
    website: 'https://www.arq.una.py',
    tags: ['diseño', 'productos', 'gráfico']
  },
  {
    id: 'fada-05',
    name: 'Licenciatura en Música',
    faculty: 'Facultad de Arquitectura, Diseño y Arte',
    duration: '10 semestres',
    hours: 3689,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Formación musical superior en interpretación, educación y composición.',
    profile: ['Músico profesional.', 'Docente de música.', 'Investigador.'],
    shifts: ['Mañana', 'Tarde'],
    admissionCalendar: 'Diciembre a Febrero (Audición)',
    admissionRequirements: ['Certificado de Estudios', 'Título de Bachiller', 'Certificado Estudios Musicales'],
    admissionExams: ['Lenguaje Musical', 'Entrenamiento Auditivo', 'Medio de Expresión (Instrumento)', 'Comunicación'],
    contactEmail: 'limus.info@fada.una.py',
    website: 'https://www.arq.una.py',
    tags: ['música', 'arte', 'instrumento']
  },
  {
    id: 'fada-06',
    name: 'Licenciatura en Danza',
    faculty: 'Facultad de Arquitectura, Diseño y Arte',
    duration: '8 semestres',
    hours: 3162,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Formación profesional en danza, creación e investigación.',
    profile: ['Bailarín.', 'Coreógrafo.', 'Docente de danza.'],
    shifts: ['Mañana'],
    admissionCalendar: 'Febrero (Examen Físico)',
    admissionRequirements: ['Certificado de Estudios', 'Título de Bachiller', 'Certificado Estudios Danza'],
    admissionExams: ['Creatividad', 'Comunicación', 'Técnica de la Danza', 'Historia de la Danza'],
    contactEmail: 'licdanza@fada.una.py',
    website: 'https://www.arq.una.py',
    tags: ['danza', 'baile', 'arte']
  },
  {
    id: 'fada-07',
    name: 'Licenciatura en Educación Artística',
    faculty: 'Facultad de Arquitectura, Diseño y Arte',
    duration: '8 semestres',
    hours: 3649,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Pedagogía y didáctica de las artes.',
    profile: ['Docente de arte.', 'Gestor educativo.'],
    shifts: ['Noche'],
    admissionCalendar: 'Noviembre a Diciembre (Inscripción)',
    admissionRequirements: ['Certificado de Estudios', 'Título de Bachiller', 'Certificado de Nacimiento'],
    admissionExams: ['Dibujo', 'Comprensión Lectora', 'Apreciación Visual'],
    contactEmail: 'sec@arq.una.py',
    website: 'https://www.arq.una.py',
    tags: ['educación', 'arte', 'enseñanza']
  },

  // --- POLITECNICA (13) ---
  {
    id: 'pol-01',
    name: 'Ingeniería en Informática',
    faculty: 'Facultad Politécnica',
    duration: '10 semestres',
    hours: 4422,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Diseño y desarrollo de sistemas informáticos complejos.',
    profile: ['Desarrollo de software.', 'Gestión de proyectos TI.'],
    shifts: ['Tarde', 'Noche'],
    admissionCalendar: 'Febrero a Mayo (Cursillo)',
    admissionRequirements: ['Certificado de Estudios', 'Título de Bachiller', 'Cédula', 'Antecedentes Policiales'],
    admissionExams: ADM_POLITECNICA_EXAMS,
    contactEmail: 'academico@pol.una.py',
    website: 'https://www.pol.una.py',
    tags: ['informática', 'software', 'tecnología']
  },
  {
    id: 'pol-02',
    name: 'Licenciatura en Ciencias Informáticas',
    faculty: 'Facultad Politécnica',
    duration: '8 semestres',
    hours: 3030,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo', 'Villarrica', 'Coronel Oviedo'],
    description: 'Análisis de sistemas y programación de computadoras.',
    profile: ['Analista de sistemas.', 'Desarrollador de aplicaciones.'],
    shifts: ['Tarde', 'Noche'],
    admissionCalendar: 'Febrero a Mayo (Cursillo)',
    admissionRequirements: ['Certificado de Estudios', 'Título de Bachiller', 'Cédula', 'Antecedentes Policiales'],
    admissionExams: ADM_POLITECNICA_EXAMS,
    contactEmail: 'academico@pol.una.py',
    website: 'https://www.pol.una.py',
    tags: ['programación', 'sistemas', 'computación']
  },
  {
    id: 'pol-03',
    name: 'Ingeniería en Sistemas de Producción',
    faculty: 'Facultad Politécnica',
    duration: '10 semestres',
    hours: 4508,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Gestión y optimización de sistemas productivos.',
    profile: ['Gestión de producción.', 'Calidad y procesos.'],
    shifts: ['Tarde', 'Noche'],
    admissionCalendar: 'Febrero a Mayo (Cursillo)',
    admissionRequirements: ['Certificado de Estudios', 'Título de Bachiller', 'Cédula', 'Antecedentes Policiales'],
    admissionExams: ADM_POLITECNICA_EXAMS,
    contactEmail: 'academico@pol.una.py',
    website: 'https://www.pol.una.py',
    tags: ['producción', 'industria', 'gestión']
  },
  {
    id: 'pol-04',
    name: 'Ingeniería en Ciencias de los Materiales',
    faculty: 'Facultad Politécnica',
    duration: '10 semestres',
    hours: 3896,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Estudio y desarrollo de nuevos materiales.',
    profile: ['Investigación de materiales.', 'Procesos industriales.'],
    shifts: ['Mañana', 'Tarde'],
    admissionCalendar: 'Febrero a Mayo (Cursillo)',
    admissionRequirements: ['Certificado de Estudios', 'Título de Bachiller', 'Cédula', 'Antecedentes Policiales'],
    admissionExams: ADM_POLITECNICA_EXAMS,
    contactEmail: 'academico@pol.una.py',
    website: 'https://www.pol.una.py',
    tags: ['materiales', 'ciencia', 'investigación']
  },
  {
    id: 'pol-05',
    name: 'Ingeniería en Electrónica',
    faculty: 'Facultad Politécnica',
    duration: '10 semestres',
    hours: 4211,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Énfasis en electrónica médica, control industrial o teleprocesamiento.',
    profile: ['Sistemas electrónicos.', 'Automatización.'],
    shifts: ['Mañana', 'Tarde'],
    admissionCalendar: 'Febrero a Mayo (Cursillo)',
    admissionRequirements: ['Certificado de Estudios', 'Título de Bachiller', 'Cédula', 'Antecedentes Policiales'],
    admissionExams: ADM_POLITECNICA_EXAMS,
    contactEmail: 'academico@pol.una.py',
    website: 'https://www.pol.una.py',
    tags: ['electrónica', 'control', 'tecnología']
  },
  {
    id: 'pol-06',
    name: 'Ingeniería en Marketing',
    faculty: 'Facultad Politécnica',
    duration: '10 semestres',
    hours: 4167,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Gestión estratégica de marketing y negocios.',
    profile: ['Estrategias de mercado.', 'Gestión comercial.'],
    shifts: ['Mañana', 'Tarde', 'Noche'],
    admissionCalendar: 'Febrero a Mayo (Cursillo)',
    admissionRequirements: ['Certificado de Estudios', 'Título de Bachiller', 'Cédula', 'Antecedentes Policiales'],
    admissionExams: ADM_POLITECNICA_EXAMS,
    contactEmail: 'marketing@pol.una.py',
    website: 'https://www.pol.una.py',
    tags: ['marketing', 'negocios', 'ventas']
  },
  {
    id: 'pol-07',
    name: 'Ingeniería en Electricidad',
    faculty: 'Facultad Politécnica',
    duration: '10 semestres',
    hours: 4215,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Sistemas eléctricos de potencia y distribución.',
    profile: ['Proyectos eléctricos.', 'Mantenimiento de redes.'],
    shifts: ['Tarde', 'Noche'],
    admissionCalendar: 'Febrero a Mayo (Cursillo)',
    admissionRequirements: ['Certificado de Estudios', 'Título de Bachiller', 'Cédula', 'Antecedentes Policiales'],
    admissionExams: ADM_POLITECNICA_EXAMS,
    contactEmail: 'academico@pol.una.py',
    website: 'https://www.pol.una.py',
    tags: ['electricidad', 'energía', 'potencia']
  },
  {
    id: 'pol-08',
    name: 'Ingeniería Aeronáutica',
    faculty: 'Facultad Politécnica',
    duration: '10 semestres',
    hours: 4878,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Diseño y mantenimiento de aeronaves y sistemas aeronáuticos.',
    profile: ['Mantenimiento aeronáutico.', 'Gestión aeroportuaria.'],
    shifts: ['Mañana', 'Tarde'],
    admissionCalendar: 'Febrero a Mayo (Cursillo)',
    admissionRequirements: ['Certificado de Estudios', 'Título de Bachiller', 'Cédula', 'Antecedentes Policiales'],
    admissionExams: ADM_POLITECNICA_EXAMS,
    contactEmail: 'academico@pol.una.py',
    website: 'https://www.pol.una.py',
    tags: ['aviones', 'aeronáutica', 'vuelo']
  },
  {
    id: 'pol-09',
    name: 'Licenciatura en Electricidad',
    faculty: 'Facultad Politécnica',
    duration: '8 semestres',
    hours: 2883,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo', 'Villarrica'],
    description: 'Instalaciones eléctricas y sistemas de energía.',
    profile: ['Instalaciones eléctricas.', 'Mantenimiento eléctrico.'],
    shifts: ['Noche'],
    admissionCalendar: 'Febrero a Mayo (Cursillo)',
    admissionRequirements: ['Certificado de Estudios', 'Título de Bachiller', 'Cédula', 'Antecedentes Policiales'],
    admissionExams: ADM_POLITECNICA_EXAMS,
    contactEmail: 'academico@pol.una.py',
    website: 'https://www.pol.una.py',
    tags: ['electricidad', 'técnico', 'instalaciones']
  },
  {
    id: 'pol-10',
    name: 'Licenciatura en Gestión de la Hospitalidad',
    faculty: 'Facultad Politécnica',
    duration: '8 semestres',
    hours: 2790,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo', 'Villarrica'],
    description: 'Gestión de hotelería, turismo y gastronomía.',
    profile: ['Gestión hotelera.', 'Turismo.', 'Gastronomía.'],
    shifts: ['Tarde', 'Noche'],
    admissionCalendar: 'Febrero a Mayo (Cursillo)',
    admissionRequirements: ['Certificado de Estudios', 'Título de Bachiller', 'Cédula', 'Antecedentes Policiales'],
    admissionExams: ADM_POLITECNICA_EXAMS,
    contactEmail: 'academico@pol.una.py',
    website: 'https://www.pol.una.py',
    tags: ['hotel', 'turismo', 'gastronomía']
  },
  {
    id: 'pol-11',
    name: 'Licenciatura en Ciencias de la Información',
    faculty: 'Facultad Politécnica',
    duration: '9 semestres',
    hours: 3173,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo', 'Villarrica', 'Coronel Oviedo'],
    description: 'Gestión de la información, bibliotecología y archivología.',
    profile: ['Gestión documental.', 'Bibliotecas.'],
    shifts: ['Tarde', 'Noche'],
    admissionCalendar: 'Febrero a Mayo (Cursillo)',
    admissionRequirements: ['Certificado de Estudios', 'Título de Bachiller', 'Cédula', 'Antecedentes Policiales'],
    admissionExams: ADM_POLITECNICA_EXAMS,
    contactEmail: 'academico@pol.una.py',
    website: 'https://www.pol.una.py',
    tags: ['información', 'biblioteca', 'archivo']
  },
  {
    id: 'pol-12',
    name: 'Licenciatura en Ciencias Atmosféricas',
    faculty: 'Facultad Politécnica',
    duration: '8 semestres',
    hours: 3323,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Estudio del clima y fenómenos meteorológicos.',
    profile: ['Meteorología.', 'Climatología.'],
    shifts: ['Mañana', 'Tarde'],
    admissionCalendar: 'Febrero a Mayo (Cursillo)',
    admissionRequirements: ['Certificado de Estudios', 'Título de Bachiller', 'Cédula', 'Antecedentes Policiales'],
    admissionExams: ADM_POLITECNICA_EXAMS,
    contactEmail: 'academico@pol.una.py',
    website: 'https://www.pol.una.py',
    tags: ['clima', 'meteorología', 'tiempo']
  },
  {
    id: 'pol-13',
    name: 'Ingeniería en Energía',
    faculty: 'Facultad Politécnica',
    duration: '10 semestres',
    hours: 4470,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Fuentes de energía, eficiencia energética y sostenibilidad.',
    profile: ['Proyectos energéticos.', 'Energías renovables.'],
    shifts: ['Mañana', 'Tarde'],
    admissionCalendar: 'Febrero a Mayo (Cursillo)',
    admissionRequirements: ['Certificado de Estudios', 'Título de Bachiller', 'Cédula', 'Antecedentes Policiales'],
    admissionExams: ADM_POLITECNICA_EXAMS,
    contactEmail: 'academico@pol.una.py',
    website: 'https://www.pol.una.py',
    tags: ['energía', 'sostenibilidad', 'renovable']
  },

  // --- FACEN (13) ---
  {
    id: 'facen-01',
    name: 'Licenciatura en Ciencias Mención Matemática Pura',
    faculty: 'Facultad de Ciencias Exactas y Naturales',
    duration: '8 semestres',
    hours: 2925,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Investigación y desarrollo en matemáticas.',
    profile: ['Investigación matemática.', 'Docencia universitaria.'],
    shifts: ['Tarde'],
    admissionCalendar: 'Febrero (1er Periodo) o Julio (2do Periodo)',
    admissionRequirements: ['Cédula de Identidad', 'Título de Bachiller', 'Certificado de Estudios'],
    admissionExams: ['Matemática', 'Química', 'Física', 'Comunicación'],
    contactEmail: 'facen@facen.una.py',
    website: 'https://www.facen.una.py',
    tags: ['matemática', 'ciencia', 'investigación']
  },
  {
    id: 'facen-02',
    name: 'Licenciatura en Ciencias Mención Matemática Estadística',
    faculty: 'Facultad de Ciencias Exactas y Naturales',
    duration: '8 semestres',
    hours: 3000,
    modality: [Modality.Presencial, Modality.Distancia],
    locations: ['San Lorenzo'],
    description: 'Análisis estadístico y modelado de datos.',
    profile: ['Análisis de datos.', 'Estadística aplicada.'],
    shifts: ['Tarde', 'Noche'],
    admissionCalendar: 'Febrero (1er Periodo) o Julio (2do Periodo)',
    admissionRequirements: ['Cédula de Identidad', 'Título de Bachiller', 'Certificado de Estudios'],
    admissionExams: ['Matemática', 'Química', 'Física', 'Comunicación'],
    contactEmail: 'facen@facen.una.py',
    website: 'https://www.facen.una.py',
    tags: ['estadística', 'datos', 'matemática']
  },
  {
    id: 'facen-03',
    name: 'Licenciatura en Ciencias Mención Química',
    faculty: 'Facultad de Ciencias Exactas y Naturales',
    duration: '8 semestres',
    hours: 3000,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Investigación y aplicación de la química.',
    profile: ['Análisis químico.', 'Investigación.'],
    shifts: ['Tarde'],
    admissionCalendar: 'Febrero (1er Periodo) o Julio (2do Periodo)',
    admissionRequirements: ['Cédula de Identidad', 'Título de Bachiller', 'Certificado de Estudios'],
    admissionExams: ['Matemática', 'Química', 'Física', 'Comunicación'],
    contactEmail: 'facen@facen.una.py',
    website: 'https://www.facen.una.py',
    tags: ['química', 'ciencia', 'laboratorio']
  },
  {
    id: 'facen-04',
    name: 'Licenciatura en Ciencias Mención Física',
    faculty: 'Facultad de Ciencias Exactas y Naturales',
    duration: '8 semestres',
    hours: 2910,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Estudio de las leyes físicas del universo.',
    profile: ['Investigación física.', 'Docencia.'],
    shifts: ['Tarde'],
    admissionCalendar: 'Febrero (1er Periodo) o Julio (2do Periodo)',
    admissionRequirements: ['Cédula de Identidad', 'Título de Bachiller', 'Certificado de Estudios'],
    admissionExams: ['Matemática', 'Química', 'Física', 'Comunicación'],
    contactEmail: 'facen@facen.una.py',
    website: 'https://www.facen.una.py',
    tags: ['física', 'ciencia', 'investigación']
  },
  {
    id: 'facen-05',
    name: 'Licenciatura en Ciencias Mención Geología',
    faculty: 'Facultad de Ciencias Exactas y Naturales',
    duration: '8 semestres',
    hours: 2895,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Estudio de la tierra y sus recursos.',
    profile: ['Exploración geológica.', 'Recursos naturales.'],
    shifts: ['Tarde'],
    admissionCalendar: 'Febrero (1er Periodo) o Julio (2do Periodo)',
    admissionRequirements: ['Cédula de Identidad', 'Título de Bachiller', 'Certificado de Estudios'],
    admissionExams: ['Matemática', 'Química', 'Física', 'Comunicación'],
    contactEmail: 'facen@facen.una.py',
    website: 'https://www.facen.una.py',
    tags: ['tierra', 'geología', 'minería']
  },
  {
    id: 'facen-06',
    name: 'Licenciatura en Ciencias Mención Biología',
    faculty: 'Facultad de Ciencias Exactas y Naturales',
    duration: '8 semestres',
    hours: 3000,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Estudio de la vida y los ecosistemas.',
    profile: ['Investigación biológica.', 'Conservación.'],
    shifts: ['Tarde'],
    admissionCalendar: 'Febrero (1er Periodo) o Julio (2do Periodo)',
    admissionRequirements: ['Cédula de Identidad', 'Título de Bachiller', 'Certificado de Estudios'],
    admissionExams: ['Matemática', 'Química', 'Física', 'Comunicación'],
    contactEmail: 'facen@facen.una.py',
    website: 'https://www.facen.una.py',
    tags: ['biología', 'naturaleza', 'vida']
  },
  {
    id: 'facen-07',
    name: 'Licenciatura en Tecnología de Producción',
    faculty: 'Facultad de Ciencias Exactas y Naturales',
    duration: '8 semestres',
    hours: 3000,
    modality: [Modality.Presencial, Modality.Distancia],
    locations: ['San Lorenzo'],
    description: 'Optimización de procesos productivos industriales.',
    profile: ['Gestión de producción.', 'Procesos industriales.'],
    shifts: ['Tarde', 'Noche'],
    admissionCalendar: 'Febrero (1er Periodo) o Julio (2do Periodo)',
    admissionRequirements: ['Cédula de Identidad', 'Título de Bachiller', 'Certificado de Estudios'],
    admissionExams: ['Matemática', 'Química', 'Física', 'Comunicación'],
    contactEmail: 'facen@facen.una.py',
    website: 'https://www.facen.una.py',
    tags: ['producción', 'tecnología', 'industria']
  },
  {
    id: 'facen-08',
    name: 'Licenciatura en Educación de Ciencias Básicas y sus Tecnologías',
    faculty: 'Facultad de Ciencias Exactas y Naturales',
    duration: '8 semestres',
    hours: 3451,
    modality: [Modality.Presencial, Modality.Distancia],
    locations: ['San Lorenzo'],
    description: 'Formación docente en ciencias naturales, física y química.',
    profile: ['Docencia en ciencias.', 'Educación.'],
    shifts: ['Tarde'],
    admissionCalendar: 'Febrero (1er Periodo) o Julio (2do Periodo)',
    admissionRequirements: ['Cédula de Identidad', 'Título de Bachiller', 'Certificado de Estudios'],
    admissionExams: ['Matemática', 'Química', 'Física', 'Comunicación'],
    contactEmail: 'facen@facen.una.py',
    website: 'https://www.facen.una.py',
    tags: ['educación', 'ciencias', 'docencia']
  },
  {
    id: 'facen-09',
    name: 'Licenciatura en Educación Matemática',
    faculty: 'Facultad de Ciencias Exactas y Naturales',
    duration: '8 semestres',
    hours: 3111,
    modality: [Modality.Presencial, Modality.Distancia],
    locations: ['San Lorenzo'],
    description: 'Formación docente especializada en matemáticas.',
    profile: ['Docencia matemática.', 'Educación.'],
    shifts: ['Mañana'],
    admissionCalendar: 'Febrero (1er Periodo) o Julio (2do Periodo)',
    admissionRequirements: ['Cédula de Identidad', 'Título de Bachiller', 'Certificado de Estudios'],
    admissionExams: ['Matemática', 'Química', 'Física', 'Comunicación'],
    contactEmail: 'facen@facen.una.py',
    website: 'https://www.facen.una.py',
    tags: ['educación', 'matemática', 'docencia']
  },
  {
    id: 'facen-10',
    name: 'Licenciatura en Biotecnología',
    faculty: 'Facultad de Ciencias Exactas y Naturales',
    duration: '8 semestres',
    hours: 3060,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Aplicación tecnológica de sistemas biológicos.',
    profile: ['Biotecnología.', 'Investigación.'],
    shifts: ['Mañana'],
    admissionCalendar: 'Febrero (1er Periodo) o Julio (2do Periodo)',
    admissionRequirements: ['Cédula de Identidad', 'Título de Bachiller', 'Certificado de Estudios'],
    admissionExams: ['Matemática', 'Química', 'Física', 'Comunicación'],
    contactEmail: 'facen@facen.una.py',
    website: 'https://www.facen.una.py',
    tags: ['biotecnología', 'ciencia', 'genética']
  },
  {
    id: 'facen-11',
    name: 'Licenciatura en Radiología e Imagenología',
    faculty: 'Facultad de Ciencias Exactas y Naturales',
    duration: '8 semestres',
    hours: 2925,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Técnicas de diagnóstico por imágenes y radioterapia.',
    profile: ['Radiología.', 'Imagenología médica.'],
    shifts: ['Mañana'],
    admissionCalendar: 'Febrero (1er Periodo) o Julio (2do Periodo)',
    admissionRequirements: ['Cédula de Identidad', 'Título de Bachiller', 'Certificado de Estudios'],
    admissionExams: ['Matemática', 'Química', 'Física', 'Comunicación'],
    contactEmail: 'facen@facen.una.py',
    website: 'https://www.facen.una.py',
    tags: ['radiología', 'salud', 'imágenes']
  },
  {
    id: 'facen-12',
    name: 'Licenciatura en Física Médica',
    faculty: 'Facultad de Ciencias Exactas y Naturales',
    duration: '8 semestres',
    hours: 3180,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Aplicación de la física en medicina.',
    profile: ['Física médica.', 'Radioterapia.'],
    shifts: ['Mañana'],
    admissionCalendar: 'Febrero (1er Periodo) o Julio (2do Periodo)',
    admissionRequirements: ['Cédula de Identidad', 'Título de Bachiller', 'Certificado de Estudios'],
    admissionExams: ['Matemática', 'Química', 'Física', 'Comunicación'],
    contactEmail: 'facen@facen.una.py',
    website: 'https://www.facen.una.py',
    tags: ['física', 'medicina', 'salud']
  },
  {
    id: 'facen-13',
    name: 'Licenciatura en Logística y Gestión del Transporte',
    faculty: 'Facultad de Ciencias Exactas y Naturales',
    duration: '8 semestres',
    hours: 2955,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Gestión de cadenas de suministro y transporte.',
    profile: ['Logística.', 'Transporte.'],
    shifts: ['Mañana'],
    admissionCalendar: 'Febrero (1er Periodo) o Julio (2do Periodo)',
    admissionRequirements: ['Cédula de Identidad', 'Título de Bachiller', 'Certificado de Estudios'],
    admissionExams: ['Matemática', 'Química', 'Física', 'Comunicación'],
    contactEmail: 'facen@facen.una.py',
    website: 'https://www.facen.una.py',
    tags: ['logística', 'transporte', 'gestión']
  },

  // --- FENOB (2) ---
  {
    id: 'fenob-01',
    name: 'Licenciatura en Enfermería',
    faculty: 'Facultad de Enfermería y Obstetricia',
    duration: '5 años',
    hours: 4876,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo', 'Concepción', 'Coronel Oviedo', 'Quiindy', 'San Estanislao'],
    description: 'Cuidado integral de la salud de las personas.',
    profile: ['Atención de enfermería.', 'Gestión en salud.'],
    shifts: ['Mañana', 'Tarde'],
    admissionCalendar: 'Febrero (Inscripción)',
    admissionRequirements: ['Bachiller', 'Certificado de Estudios', 'Cédula', 'Antecedentes'],
    admissionExams: ['Comunicación Oral y Escrita', 'Química', 'Matemática', 'Ciencias Naturales'],
    contactEmail: 'decanato@fenob.una.py',
    website: 'https://www.fenob.una.py',
    tags: ['enfermería', 'salud', 'cuidado']
  },
  {
    id: 'fenob-02',
    name: 'Licenciatura en Obstetricia',
    faculty: 'Facultad de Enfermería y Obstetricia',
    duration: '10 semestres',
    hours: 4942,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo', 'Concepción'],
    description: 'Salud sexual y reproductiva, atención del embarazo y parto.',
    profile: ['Obstetricia.', 'Salud materna.'],
    shifts: ['Mañana', 'Tarde'],
    admissionCalendar: 'Febrero (Inscripción)',
    admissionRequirements: ['Bachiller', 'Certificado de Estudios', 'Cédula', 'Antecedentes'],
    admissionExams: ['Comunicación Oral y Escrita', 'Química', 'Matemática', 'Ciencias Naturales'],
    contactEmail: 'decanato@fenob.una.py',
    website: 'https://www.fenob.una.py',
    tags: ['obstetricia', 'salud', 'maternidad']
  },

  // --- FACSO (2) ---
  {
    id: 'facso-01',
    name: 'Licenciatura en Trabajo Social',
    faculty: 'Facultad de Ciencias Sociales',
    duration: '10 semestres',
    hours: 3330,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Intervención social para el bienestar y desarrollo.',
    profile: ['Trabajo social.', 'Políticas sociales.'],
    shifts: ['Tarde', 'Noche'],
    admissionCalendar: '26 de Enero al 20 de Febrero (Inscripción Probatorio)',
    admissionRequirements: ['Bachiller', 'Certificado de Estudios', 'Cédula'],
    admissionExams: ['História Social del Paraguay', 'Introducción a la Filosofía', 'Castellano', 'Matemática', 'TIC'],
    contactEmail: 'decanato@facso.una.py',
    website: 'https://www.facso.una.py',
    tags: ['social', 'comunidad', 'bienestar']
  },
  {
    id: 'facso-02',
    name: 'Licenciatura en Sociología',
    faculty: 'Facultad de Ciencias Sociales',
    duration: '10 semestres',
    hours: 2754,
    modality: [Modality.Presencial],
    locations: ['San Lorenzo'],
    description: 'Estudio de la sociedad y sus fenómenos.',
    profile: ['Investigación social.', 'Análisis sociológico.'],
    shifts: ['Noche'],
    admissionCalendar: '26 de Enero al 20 de Febrero (Inscripción Probatorio)',
    admissionRequirements: ['Bachiller', 'Certificado de Estudios', 'Cédula'],
    admissionExams: ['História Social del Paraguay', 'Introducción a la Filosofía', 'Castellano', 'Matemática', 'TIC'],
    contactEmail: 'decanato@facso.una.py',
    website: 'https://www.facso.una.py',
    tags: ['sociología', 'investigación', 'sociedad']
  }
];
